#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#+ and writes "hi" in the 9th time

count=0
while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 8 ]
       	then echo "Hi"
	fi
	((count++))
done
